# AI providers
- source: https://feluda.ai/ai-models
- last updated: 12-03-2026
- website: http://feluda.ai
- description: (offline) AI Workflow automation with your own desktop
- purpose: collection of AI providers
--- 
| Company URL                                                                                  | Docs URL                                                                                                                   | Description                                                                                                                   |
| -------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------- |
| [https://www.stepfun.com](https://www.stepfun.com)                                           | [https://platform.stepfun.com/docs](https://platform.stepfun.com/docs)                                                     | Shanghai AI startup building large-scale multimodal models under the Step brand, targeting top-tier reasoning benchmarks.     |
| [https://www.sensetime.com](https://www.sensetime.com)                                       | [https://platform.sensenova.cn/doc](https://platform.sensenova.cn/doc)                                                     | Hong Kong-listed AI computer-vision company expanding to LLMs via the SenseNova foundation model series.                      |
| [https://www.scaleway.com](https://www.scaleway.com)                                         | [https://www.scaleway.com/en/docs/ai-data/managed-inference/](https://www.scaleway.com/en/docs/ai-data/managed-inference/) | French cloud provider (Iliad group) offering managed AI inference with European data sovereignty.                             |
| [https://www.sarvam.ai](https://www.sarvam.ai)                                               | [https://docs.sarvam.ai](https://docs.sarvam.ai)                                                                           | Indian AI company offering speech, translation, and LLM APIs for India's 22 official languages.                               |
| [https://www.ovhcloud.com](https://www.ovhcloud.com)                                         | [https://endpoints.ai.cloud.ovh.net](https://endpoints.ai.cloud.ovh.net)                                                   | European cloud provider with AI Endpoints offering OpenAI-compatible inference anchored in EU data sovereignty.               |
| [https://www.moonshot.cn](https://www.moonshot.cn)                                           | [https://platform.moonshot.cn/docs](https://platform.moonshot.cn/docs)                                                     | Chinese AI startup behind Kimi chatbot, known for extremely long context windows and high-quality reasoning.                  |
| [https://www.minimax.io](https://www.minimax.io)                                             | [https://www.minimax.com/platform](https://www.minimax.com/platform)                                                       | Shanghai multimodal AI company behind ABAB LLMs, Hailuo video generation, and Talkie AI companion app.                        |
| [https://www.deepseek.com](https://www.deepseek.com)                                         | [https://api-docs.deepseek.com](https://api-docs.deepseek.com)                                                             | Chinese AI lab (backed by quant hedge fund High-Flyer) building frontier models at remarkably low training cost.              |
| [https://www.core42.ai](https://www.core42.ai)                                               | [https://www.core42.ai/products/jais](https://www.core42.ai/products/jais)                                                 | Abu Dhabi's sovereign AI cloud company (G42 Group), home of the Jais Arabic-first foundation model.                           |
| [https://www.baichuan-ai.com](https://www.baichuan-ai.com)                                   | [https://platform.baichuan-ai.com/docs](https://platform.baichuan-ai.com/docs)                                             | Chinese AI company by search pioneer Wang Xiaochuan, specialising in LLMs with deep medical knowledge integration.            |
| [https://www.anthropic.com](https://www.anthropic.com)                                       | [https://docs.anthropic.com](https://docs.anthropic.com)                                                                   | AI safety company building Claude — a family of reliable, interpretable, and harmless assistants.                             |
| [https://www.alibabacloud.com/product/bailian](https://www.alibabacloud.com/product/bailian) | [https://www.alibabacloud.com/help/en/model-studio](https://www.alibabacloud.com/help/en/model-studio)                     | Alibaba's cloud division providing the Qwen (通义千问) LLM family via the DashScope Model Studio API.                             |
| [https://www.ai21.com](https://www.ai21.com)                                                 | [https://docs.ai21.com](https://docs.ai21.com)                                                                             | Israeli AI company pioneering the Jamba architecture (SSM + Transformer hybrid) and enterprise-grade LLMs.                    |
| [https://www.01.ai](https://www.01.ai)                                                       | [https://platform.lingyiwanwu.com/docs](https://platform.lingyiwanwu.com/docs)                                             | AI venture by Kai-Fu Lee building the Yi model series — high-quality bilingual (Chinese–English) LLMs.                        |
| [https://stability.ai](https://stability.ai)                                                 | [https://platform.stability.ai/docs/api-reference](https://platform.stability.ai/docs/api-reference)                       | Pioneer of open-weight generative AI for images, video, audio, and language via Stable Diffusion and beyond.                  |
| [https://replicate.com](https://replicate.com)                                               | [https://replicate.com/docs](https://replicate.com/docs)                                                                   | Cloud platform for running ML models via a simple API — now part of Cloudflare's AI platform.                                 |
| [https://openrouter.ai](https://openrouter.ai)                                               | [https://openrouter.ai/docs](https://openrouter.ai/docs)                                                                   | Unified LLM API gateway routing requests to 300+ models from OpenAI, Anthropic, Meta, Mistral, and more.                      |
| [https://openai.com](https://openai.com)                                                     | [https://platform.openai.com/docs](https://platform.openai.com/docs)                                                       | AI research and deployment company building GPT and o-series models; creator of ChatGPT.                                      |
| [https://open.bigmodel.cn](https://open.bigmodel.cn)                                         | [https://open.bigmodel.cn/dev/api](https://open.bigmodel.cn/dev/api)                                                       | Tsinghua University spin-off building the GLM series of bilingual (Chinese–English) large language models.                    |
| [https://ollama.com](https://ollama.com)                                                     | [https://github.com/ollama/ollama/blob/main/docs/api.md](https://github.com/ollama/ollama/blob/main/docs/api.md)           | Run large language models locally on Mac, Linux, or Windows with a single command.                                            |
| [https://mistral.ai](https://mistral.ai)                                                     | [https://docs.mistral.ai](https://docs.mistral.ai)                                                                         | French AI startup building flagship open-weight and commercial models; known for efficiency and European AI sovereignty.      |
| [https://krutrim.com](https://krutrim.com)                                                   | [https://cloud.olakrutrim.com/docs](https://cloud.olakrutrim.com/docs)                                                     | India's first AI unicorn, building LLMs rooted in Indic languages and AI cloud infrastructure.                                |
| [https://huggingface.co](https://huggingface.co)                                             | [https://huggingface.co/docs/api-inference](https://huggingface.co/docs/api-inference)                                     | The 'GitHub of AI' — an open platform hosting 500,000+ models, 100,000+ datasets, and Spaces for demos.                       |
| [https://groq.com](https://groq.com)                                                         | [https://console.groq.com/docs/overview](https://console.groq.com/docs/overview)                                           | AI chip company and cloud provider offering the world's fastest LLM inference via its proprietary LPU hardware.               |
| [https://fireworks.ai](https://fireworks.ai)                                                 | [https://docs.fireworks.ai](https://docs.fireworks.ai)                                                                     | Fast, cost-efficient inference and fine-tuning platform for open-source models, optimised for production compound-AI systems. |
| [https://deepinfra.com](https://deepinfra.com)                                               | [https://deepinfra.com/docs](https://deepinfra.com/docs)                                                                   | Serverless GPU inference cloud for open-weight LLMs with an OpenAI-compatible API.                                            |
| [https://cohere.com](https://cohere.com)                                                     | [https://docs.cohere.com](https://docs.cohere.com)                                                                         | Enterprise NLP company offering Command (generation), Embed (search/RAG), and Rerank APIs for business AI.                    |
| [https://aleph-alpha.com](https://aleph-alpha.com)                                           | [https://docs.aleph-alpha.com](https://docs.aleph-alpha.com)                                                               | German AI company building explainable, European-sovereign LLMs for enterprises and governments.                              |
| [https://x.ai](https://x.ai)                                                                 | [https://docs.x.ai](https://docs.x.ai)                                                                                     | Elon Musk's AI company building Grok — a frontier reasoning model connected to real-time X (Twitter) data.                    |
| [https://www.volcengine.com/product/ark](https://www.volcengine.com/product/ark)             | [https://www.volcengine.com/docs/82379](https://www.volcengine.com/docs/82379)                                             | Technology giant behind TikTok and Toutiao, offering Doubao LLMs via the Volcano Engine Ark AI platform.                      |
| [https://www.together.ai](https://www.together.ai)                                           | [https://docs.together.ai](https://docs.together.ai)                                                                       | AI-native cloud providing fast inference, fine-tuning, and training for open-source foundation models.                        |
